=== vaydominika/VM3DIRWebXML/VM3DIR_0924/VM3DIR_kurzusfelvetel.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT VM3DIR_kurzusfelvetel (hallgato, kurzusok)>
<!ATTLIST VM3DIR_kurzusfelvetel
          tanÃ©v CDATA #REQUIRED
          egyetem CDATA #REQUIRED>

<!ELEMENT hallgato (hnev, szulev, szak)>
<!ELEMENT kurzusok (kurzus*)>

<!ELEMENT kurzus (kurzusnev, kredit, hely, idopont, oktato, oraado?)>
<!ATTLIST kurzus
          id CDATA #REQUIRED
          jovahagyas (igen|nem) "nem"
          nyelv CDATA #IMPLIED>

<!ELEMENT hnev (#PCDATA)>
<!ELEMENT szulev (#PCDATA)>
<!ELEMENT szak (#PCDATA)>
<!ATTLIST szak
          evf CDATA #REQUIRED>

<!ELEMENT kurzusnev (#PCDATA)>
<!ELEMENT kredit (#PCDATA)>
<!ELEMENT hely (#PCDATA)>
<!ELEMENT idopont (#PCDATA)>
<!ELEMENT oktato (#PCDATA)>
<!ELEMENT oraado (#PCDATA)>

=== vaydominika/VM3DIRWebXML/VM3DIR_0924/VM3DIR_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE VM3DIR_kurzusfelvetel SYSTEM "VM3DIR_kurzusfelvetel.dtd">
<VM3DIR_kurzusfelvetel tanév="2025/26" egyetem="MiskolciEgyetem">
    <hallgato>
        <hnev>Vay Dominika</hnev>
        <szulev>2003</szulev>
        <szak evf="3">Mérnökinformatikus BSc</szak>
    </hallgato>
    
    <kurzusok>
        <kurzus id="VM3DIR">
            <kurzusnev>Web technológiák 1.</kurzusnev>
            <kredit>4</kredit>
            <hely>5. előadó</hely>
            <idopont>Hétfő 10:00-12:00</idopont>
            <oktato>Agárdi Anita</oktato>
        </kurzus>
        
        <kurzus id="VM3DIR" jovahagyas="igen" nyelv="magyar">
            <kurzusnev>Mobil programozási alapok</kurzusnev>
            <kredit>3</kredit>
            <hely>Infó épület 1. emelet 101. terem</hely>
            <idopont>Hétfő 16:00-18:00</idopont>
            <oktato>Agárdi Anita</oktato>
            <oraado>Óraadó neve</oraado>
        </kurzus>
        
        <kurzus id="VM3DIR">
            <kurzusnev>Mesterséges Intelligencia alapok</kurzusnev>
            <kredit>4</kredit>
            <hely>32. előadó</hely>
            <idopont>Kedd 10:00-12:00</idopont>
            <oktato>Kunné Dr. Tamás Judit</oktato>
        </kurzus>
        
        <kurzus id="VM3DIR" jovahagyas="nem" nyelv="magyar">
            <kurzusnev>UNIX rendszergazda</kurzusnev>
            <kredit>3</kredit>
            <hely>Infó épület 1. emelet 103. terem</hely>
            <idopont>Szerda 08:00-10:00</idopont>
            <oktato>Dr. Baksa Attila</oktato>
            <oraado>Dr. Nagy János</oraado>
        </kurzus>
        
        <kurzus id="VM3DIR">
            <kurzusnev>Webes adatkezelő környezetek</kurzusnev>
            <kredit>4</kredit>
            <hely>A1/310</hely>
            <idopont>Szerda 08:00-10:00</idopont>
            <oktato>Dr. Kovács László József</oktato>
        </kurzus>
        
        <kurzus id="VM3DIR">
            <kurzusnev>Elektronika-elektrotechnika</kurzusnev>
            <kredit>3</kredit>
            <hely>3. előadó</hely>
            <idopont>Hétfő 08:00-10:00</idopont>
            <oktato>Szabó Norbert</oktato>
        </kurzus>
    </kurzusok>
</VM3DIR_kurzusfelvetel>
